
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication3.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Hastane
{

    public int CustomerID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public System.DateTime Date { get; set; }

    public string Telefon { get; set; }

    public string Text { get; set; }

    public string Mail { get; set; }

}

}
